/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.juego.logica;

import javax.swing.Timer;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author rami
 */
public class JFrame_Main_Menu extends javax.swing.JFrame {

    Timer t;
    int contadorclicks = 5;
    int contadorpc = 10;
    Random rand = new Random();
    ImageIcon[] imagenes = new ImageIcon[52];
    ImageIcon imagen1 = new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/card.jpg"));
    int array[] = new int[10];
    /**
     * Creates new form JFrame_Main_Menu
     */
    public JFrame_Main_Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelJugador1 = new javax.swing.JPanel();
        jButtonCarta1J1 = new javax.swing.JButton();
        jButtonCarta2J1 = new javax.swing.JButton();
        jButtonCarta3J1 = new javax.swing.JButton();
        jButtonCarta4J1 = new javax.swing.JButton();
        jButtonCarta5J1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de 21 (EVA EDITION V1)");
        setResizable(false);

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/background.jpg"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);

        jLabelTitulo.setFont(new java.awt.Font("Courier", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Juego de 21");

        jPanelJugador1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelJugador1.setOpaque(false);

        jButtonCarta1J1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCarta1J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/card.jpg"))); // NOI18N
        jButtonCarta1J1.setBorderPainted(false);
        jButtonCarta1J1.setContentAreaFilled(false);

        jButtonCarta2J1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCarta2J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/card.jpg"))); // NOI18N
        jButtonCarta2J1.setBorderPainted(false);
        jButtonCarta2J1.setContentAreaFilled(false);

        jButtonCarta3J1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCarta3J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/card.jpg"))); // NOI18N
        jButtonCarta3J1.setBorderPainted(false);
        jButtonCarta3J1.setContentAreaFilled(false);

        jButtonCarta4J1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCarta4J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/card.jpg"))); // NOI18N
        jButtonCarta4J1.setBorderPainted(false);
        jButtonCarta4J1.setContentAreaFilled(false);

        jButtonCarta5J1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCarta5J1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/ui/card.jpg"))); // NOI18N
        jButtonCarta5J1.setBorderPainted(false);
        jButtonCarta5J1.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelJugador1Layout = new javax.swing.GroupLayout(jPanelJugador1);
        jPanelJugador1.setLayout(jPanelJugador1Layout);
        jPanelJugador1Layout.setHorizontalGroup(
            jPanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJugador1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCarta1J1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCarta2J1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCarta3J1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCarta4J1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCarta5J1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelJugador1Layout.setVerticalGroup(
            jPanelJugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonCarta1J1)
            .addComponent(jButtonCarta2J1)
            .addComponent(jButtonCarta3J1)
            .addComponent(jButtonCarta4J1)
            .addComponent(jButtonCarta5J1)
        );

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap(335, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(266, 266, 266))
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelJugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Main_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCarta1J1;
    private javax.swing.JButton jButtonCarta2J1;
    private javax.swing.JButton jButtonCarta3J1;
    private javax.swing.JButton jButtonCarta4J1;
    private javax.swing.JButton jButtonCarta5J1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelJugador1;
    private javax.swing.JTextField jTextField1;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    // End of variables declaration//GEN-END:variables
}
